/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace hronaspdotnet.Domain;

/// <summary>
/// DayOfWeek enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum DayOfWeek
{
    Monday=1,Tuesday=2,Wednesday=3,Thursday=4,Friday=5,Saturday=6,Sunday=7
}

/// <summary>
/// Extension of capabilities for the DayOfWeek enum
/// </summary>
public static class DayOfWeekExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<DayOfWeek> GetValues()
    {
        return Enum.GetValues<DayOfWeek>().ToList();
    }

    public static DayOfWeek GetDefaultValue()
    {
        return Enum.GetValues<DayOfWeek>().First();
    }

    public static DayOfWeek WhichOne(string name)
    {
        if (Enum.TryParse<DayOfWeek>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



